### ISSUE TITLE
Kover failed on certain test cases 

### ISSUE THREAD

**Issue by coffee-and-tea** [Kotlin/kotlinx-kover#306]
Kover starts to having this issue after we add some customized annotation to data class with below:

[2023.02.22 14:13:34] (Coverage): Unexpected error: java.lang.NoClassDefFoundError: Could not initialize class com.intellij.rt.coverage.util.CoverageIOUtil
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: Could not initialize class com.intellij.rt.coverage.util.CoverageIOUtil
        at com.intellij.rt.coverage.util.ErrorReporter.reportError(ErrorReporter.java:64)
        at com.intellij.rt.coverage.instrumentation.SaveHook.save(SaveHook.java:85)
        at com.intellij.rt.coverage.instrumentation.SaveHook.run(SaveHook.java:55)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by zuevmaxim** [comment]
@coffee-and-tea Could you please share the content of `build/kover/errors` directories from the project where you are running tests?

Is your project open source? If yes, please share the link. Alternatively, is it possible to reproduce the error on a small project?

**Comment by zuevmaxim** [comment]
@coffee-and-tea Could you also rerun your tests with the latest `1.0.708 ` engine version?

for Kotlin Gradle script
```
kover {
    engine.set(kotlinx.kover.api.IntellijEngine("1.0.708"))
}
```
for Groovy
```
kover {
    engine = new kotlinx.kover.api.IntellijEngine("1.0.708")
}
```
And do you use the latest kover version `0.6.1`?

**Comment by coffee-and-tea** [comment]
@zuevmaxim thanks, the log file test.log only has below:
```
[2023.02.22 14:13:34] (Coverage): Unexpected error: java.lang.NoClassDefFoundError: Could not initialize class com.intellij.rt.coverage.util.CoverageIOUtil
Exception in thread "Thread-0" java.lang.NoClassDefFoundError: Could not initialize class com.intellij.rt.coverage.util.CoverageIOUtil
at com.intellij.rt.coverage.util.ErrorReporter.reportError(ErrorReporter.java:64)
at com.intellij.rt.coverage.instrumentation.SaveHook.save(SaveHook.java:85)
at com.intellij.rt.coverage.instrumentation.SaveHook.run(SaveHook.java:55)
at java.base/java.lang.Thread.run(Thread.java:834)
```

it's not open source unfortunately, let me try to reproduce that and share. 
> @coffee-and-tea Could you please share the content of `build/kover/errors` directories from the project where you are running tests?
> 
> Is your project open source? If yes, please share the link. Alternatively, is it possible to reproduce the error on a small project?

**Comment by coffee-and-tea** [comment]
@zuevmaxim same result with `1.0.708` and yes, I have latest version of kover `0.6.1`

> @coffee-and-tea Could you also rerun your tests with the latest `1.0.708 ` engine version?
> 
> for Kotlin Gradle script
> 
> ```
> kover {
>     engine.set(kotlinx.kover.api.IntellijEngine("1.0.708"))
> }
> ```
> 
> for Groovy
> 
> ```
> kover {
>     engine = new kotlinx.kover.api.IntellijEngine("1.0.708")
> }
> ```
> 
> And do you use the latest kover version `0.6.1`?

**Comment by zuevmaxim** [comment]
> same result with `1.0.708`

@coffee-and-tea Could you please share the exception when running with `1.0.708` version?

**Comment by coffee-and-tea** [comment]
> > same result with `1.0.708`
> 
> @coffee-and-tea Could you please share the exception when running with `1.0.708` version?

here the error: 

```
[2023.02.24 09:08:02] (Coverror: Could not initialize class com.intellij.rt.coverage.util.CoverageIOUtil
                           	at com.intellij.rt.coverage.instrumentation.SaveHook.save(SaveHook.java:109)
                           	at com.intellij.rt.coverage.instrumentation.SaveHook.save(SaveHook.java:81)
                           	at com.intellij.rt.coverage.instrumentation.SaveHook.run(SaveHook.java:55)
                           	at java.base/java.lang.Thread.run(Thread.java:834)rage): Unexpected error
java.lang.NoClassDefFoundError: Could not initialize class com.intellij.rt.coverage.util.CoverageIOUtil
	at com.intellij.rt.coverage.instrumentation.SaveHook.save(SaveHook.java:109)
	at com.intellij.rt.coverage.instrumentation.SaveHook.save(SaveHook.java:81)
	at com.intellij.rt.coverage.instrumentation.SaveHook.run(SaveHook.java:55)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by zuevmaxim** [comment]
@coffee-and-tea I think that the engine version set-up was not successful in your case because this version does not have `com.intellij.rt.coverage.instrumentation.SaveHook` class
Could you please check that you specified this setting in all your projects? After this, please clear your project, rerun the tests and share an exception

**Comment by coffee-and-tea** [comment]
@zuevmaxim you are right, adding to top project level wasn't enough:
```
kover {
    isDisabled.set(false)
    engine.set(kotlinx.kover.api.IntellijEngine("1.0.708"))
}
```

I had to add to subprojects:
```
subproject {
    kover {
        isDisabled.set(false)
        engine.set(kotlinx.kover.api.IntellijEngine("1.0.708"))
    }
}
```

Now it works with `1.0.708` no more errors.  thanks

@zuevmaxim pls help me to understand what's the issue here? is there an IntelliJ bug in the previous version that I use? Thanks for your help again!

**Comment by zuevmaxim** [comment]
@coffee-and-tea I have no exact explanation because the coverage agent jar always contains all the required classes in it, so I see no reason for NoClassDefFoundError. I asked you to try running with a newer version because there were a number of class renamings.

**Comment by coffee-and-tea** [comment]
@zuevmaxim thanks. Some more context, I only encounter this issue when I run coverage with gradle, I tried multiple version of 7.x all having this error. Although I have no issue running coverage with IntelliJ.

**Comment by zuevmaxim** [comment]
@coffee-and-tea What do you mean by running coverage with IntelliJ? Currently, Kover is not supposed for running with coverage actions in IDEA.

**Comment by coffee-and-tea** [comment]
@zuevmaxim I meant that running native coverage report from IntelliJ, which uses the same coverage engine does not have this error. Only when I run gradle with kover having this issue.

**Comment by zuevmaxim** [comment]
@coffee-and-tea Did you use 'Run with coverage' action in IDEA to run tests with gradle and kover enabled?

**Comment by coffee-and-tea** [comment]
No, in IntelliJ I have running tests with IntelliJ IDEA configured.
